dev:
    image: nginx:1.9
    ports:
        - "80"
    volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./:/usr/share/nginx/html:ro
    environment:
        - VIRTUAL_HOST=explorer.turbasen.privat
        - VIRTUAL_PORT=80
